gemini_api_key: "AIzaSyB7AHiCU_G9nyYIsYKWx9zi27mZLpVFkVo" # Your Google Gemini API key here
# openai_api_key: "" 
model: "gemini-2.5-flash" # Default model is gemini-1.5-flash.

# Translation Settings
source_lang: "English"
target_lang: "Vietnamese"

# Performance Settings
max_concurrent: 100
max_chunk_size: 5000
requests_per_minute: 4 # Limit RPM to Avoid 429 Errors